export default (strings_en = {
  PERMISSION_UNAVAILABLE: 'This feature is not available on this device.',
  PERMISSION_DENIED:
    'The permission has not been requested or is denied but requestable',
  PERMISSION_GRANTED: 'The permission is granted',
  PERMISSION_BLOCKED: 'The permission is denied and not requestable anymor',
  setting_title: 'Settings',
  news_title: 'News',
  title_save:'Save',
  search_title: 'Search',
  sign_btn: 'Sign In',
  list_language: 'Language',
  list_datausage: 'Data Usage',
  list_notification: 'Notification',
  list_darkmode: 'Dark Mode',
  list_whatsapp: 'News On Whatsapp',
  list_terms: 'Terms & Conditions',
  list_feedback: 'Feedback',
  list_share: 'Share',
  list_about: 'About',
  language_en: 'English',
  label_enable: 'Enabled',
  title_bbc: 'BBC News',
  title_toi: 'Time of India',
  title_ht: 'Hindustan times',
  title_nt: 'NewYork Times',
  title_cnn: 'CNN News',
  title_ndtv: 'NDTV Channel',
  title_follow:'Follow',
  title_following: 'Following',
  title_newswhatsapp : 'News on WhatsApp',
  list_entertainment: 'Entertainment',
  list_sports: 'Sports',
  list_business: 'Business',
  list_science: 'Science',
  list_general: 'General',
  list_health: 'Health',
  list_technology: 'Technology',
  language_hindi: 'Hindi',
  

})